<a href="https://colab.research.google.com/github/anuragpatil811/Machine-Learning/blob/main/Standardization_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [15]:
df = pd.read_csv('/content/loan.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [10]:
df.drop(columns='Loan_ID', inplace=True)

In [11]:
df["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [12]:
le = LabelEncoder()
df['Property_Area'] = le.fit_transform(df['Property_Area'])

In [13]:
df['Property_Area'].unique()

array([2, 0, 1])

In [16]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [18]:
df['Dependents'].dtype

dtype('O')

In [21]:
df.dropna(inplace=True)

In [22]:
df['Dependents'].unique()

array(['1', '0', '2', '3+'], dtype=object)

In [23]:
df['Dependents'] = df['Dependents'].replace('3+', '3')

In [24]:
df['Dependents'] = df['Dependents'].astype(int)

In [25]:
from sklearn.preprocessing import StandardScaler

In [27]:
ss = StandardScaler()
df['Dependents_ss'] = ss.fit_transform(df[['Dependents']])

In [28]:
df['Dependents_ss'].head()

1    0.218599
2   -0.762033
3   -0.762033
4   -0.762033
5    1.199231
Name: Dependents_ss, dtype: float64